import { jsPDF } from 'jspdf';

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportAsJSON(history) {
  const text = JSON.stringify(history, null, 2);
  downloadBlob(text, 'apipulse-report.json', 'application/json');
}

function escapeCsvField(value) {
  const s = value == null ? '' : String(value);
  if (/[",\n\r]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

export function exportAsCSV(history) {
  const headers = ['Timestamp', 'Method', 'URL', 'Status', 'ResponseTime(ms)', 'IsError'];
  const lines = [headers.join(',')];
  for (const item of history) {
    const row = [
      escapeCsvField(item.timestamp),
      escapeCsvField(item.method),
      escapeCsvField(item.url),
      escapeCsvField(item.status ?? ''),
      escapeCsvField(item.responseTime),
      escapeCsvField(!!item.isError),
    ];
    lines.push(row.join(','));
  }
  downloadBlob(lines.join('\n'), 'apipulse-report.csv', 'text/csv;charset=utf-8');
}

function truncate(str, max) {
  const s = str == null ? '' : String(str);
  return s.length <= max ? s : `${s.slice(0, max - 1)}…`;
}

/**
 * @param {Array} history
 * @param {{ totalRequests: number, avgResponseTime: number, successRate: number }} stats
 */
export function exportAsPDF(history, stats) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = 18;

  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);
  doc.text('APIPulse ⚡ — API Test Report', margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  const generated = new Date().toLocaleString();
  doc.text(`Generated: ${generated}`, margin, y);
  y += 12;

  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text('Summary', margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  const total = stats?.totalRequests ?? history.length;
  const avg = stats?.avgResponseTime ?? 0;
  const rate = stats?.successRate ?? 0;
  doc.text(`Total requests: ${total}`, margin, y);
  y += 6;
  doc.text(`Avg response time: ${avg}ms`, margin, y);
  y += 6;
  doc.text(`Success rate: ${rate}%`, margin, y);
  y += 12;

  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text('Requests', margin, y);
  y += 8;

  doc.setFontSize(9);
  const colMethod = margin;
  const colUrl = margin + 22;
  const colStatus = pageW - margin - 38;
  const colTime = pageW - margin - 18;

  doc.setTextColor(100, 100, 100);
  doc.text('Method', colMethod, y);
  doc.text('URL', colUrl, y);
  doc.text('Status', colStatus, y);
  doc.text('Time', colTime, y);
  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  doc.setTextColor(50, 50, 50);
  const pageH = doc.internal.pageSize.getHeight();
  const rowH = 6;
  const maxUrlW = colStatus - colUrl - 4;

  for (const item of history) {
    if (y > pageH - 24) {
      doc.addPage();
      y = margin + 6;
    }
    const method = String(item.method || '');
    const url = truncate(item.url || '', 52);
    const status = item.isError ? 'Err' : String(item.status ?? '');
    const time = `${item.responseTime ?? 0}ms`;

    doc.text(method, colMethod, y);
    doc.text(url, colUrl, y, { maxWidth: maxUrlW });
    doc.text(status, colStatus, y);
    doc.text(time, colTime, y);
    y += rowH;
  }

  const footerY = pageH - 10;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text('Generated by APIPulse', margin, footerY);

  doc.save('apipulse-report.pdf');
}
